package compiler

// ---------------------------------------------------------------------------
// Shared execution types used by both internal/strategy and internal/memory
//
// These are domain data types that cross the strategy/executor boundary.
// They contain NO database-specific fields — pure data structs with JSON tags.
// The internal/memory package uses these types for persistence and retrieves
// them as-is from the database.
// ---------------------------------------------------------------------------

// NodeState represents the execution state of a single node in a task graph.
type NodeState struct {
	TaskID             string `json:"taskId"`
	NodeID             string `json:"nodeId"`
	Status             string `json:"status"` // "pending" | "running" | "completed" | "failed" | "skipped"
	Output             string `json:"output"`
	RawOutput          string `json:"rawOutput,omitempty"`          // Clean tool output for interpolation
	AnalyticalEvidence string `json:"analyticalEvidence,omitempty"` // ADR-0053: structured raw data
	StructuredOutput   string `json:"structuredOutput,omitempty"`   // ADR-0055: deterministic Execution Envelope JSON
	CompletedAt        int64  `json:"completedAt"`
}

// ThoughtStep represents a single step in a Probe Node's Thought Chain.
// Each step is a stateless Local Model inference call that produces either
// a tool call or a synthesis decision.
type ThoughtStep struct {
	ID         string `json:"id"`
	ProbeID    string `json:"probeId"`
	TaskID     string `json:"taskId"`
	StepIndex  int    `json:"stepIndex"`
	Thought    string `json:"thought"`
	ToolName   string `json:"toolName,omitempty"`
	ToolArgs   string `json:"toolArgs,omitempty"`
	ToolOutput string `json:"toolOutput,omitempty"`
	Embedding  []byte `json:"embedding,omitempty"`
	CreatedAt  int64  `json:"createdAt"`
}

// ThoughtSummary represents a rolling compaction summary of a Thought Chain.
// Every N steps, recent thoughts are compressed into a summary for context efficiency.
type ThoughtSummary struct {
	ID        string `json:"id"`
	ProbeID   string `json:"probeId"`
	TaskID    string `json:"taskId"`
	StepRange string `json:"stepRange"` // e.g., "1-3", "4-6"
	Summary   string `json:"summary"`
	Embedding []byte `json:"embedding,omitempty"`
	CreatedAt int64  `json:"createdAt"`
}

// EdgeThought represents a reasoning state propagated across a DAG edge (ADR-0024).
// Generated by the Local Model when the executor traverses an edge whose target node
// has a non-zero Activation Threshold.
type EdgeThought struct {
	ID             string  `json:"id"`
	TaskID         string  `json:"taskId"`
	SourceNode     string  `json:"sourceNode"`
	TargetNode     string  `json:"targetNode"`
	Thought        string  `json:"thought"`
	GoalConfidence float64 `json:"goalConfidence"` // 0.0-1.0: sufficiency gate signal
	GoalAchieved   bool    `json:"goalAchieved"`   // Halt flag
	StepIndex      int     `json:"stepIndex"`
	CreatedAt      int64   `json:"createdAt"`
}
