// Generated by tzro init. All behavior applies to ordinary workspaces.
import { execFileSync } from "node:child_process";
import { appendFileSync, mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const binary = __TZRO_BINARY__;
const commands = ["context", "probe", "search", "impact", "skeleton", "expand", "ingest", "query", "compact", "execute"];

export default function (pi: any) {
  pi.registerTool({
    name: "tzro_execute_graph",
    label: "Tzro local workflow",
    description: __TZRO_GRAPH_DESCRIPTION__ + (process.env.TZRO_EXPERIMENTAL_RUNTIMES === "1"
      ? " Local decision/extraction workers are enabled; missing or invalid workers produce an explicit error."
      : " Local decision/extraction workers are disabled; use tool nodes."),
    promptSnippet: "Delegate several dependent local steps in one call, returning selected evidence",
    promptGuidelines: ["Use tzro_execute_graph for a known sequence of local steps. Keep intermediate data local and choose returns. Single steps can use tzro directly. Cloud reasoning and code generation stay with you."],
    parameters: __TZRO_GRAPH_SCHEMA__,
    async execute(_id: string, params: any, signal: AbortSignal, _update: any, ctx: any) {
      signal?.throwIfAborted();
      const directory = mkdtempSync(join(tmpdir(), "tzro-graph-"));
      try {
        const path = join(directory, "graph.json");
        writeFileSync(path, JSON.stringify(params.graph), { mode: 0o600 });
        const result = await pi.exec(binary, ["execute", path, "--result", "selected"], { signal, timeout: 60000, cwd: ctx.cwd });
        if (result.code !== 0 || result.killed) {
          throw new Error(result.stderr || result.stdout || `tzro exited ${result.code}`);
        }
        const value = JSON.parse(result.stdout);
        if (value.status === "failed") throw new Error(result.stdout);
        return { content: [{ type: "text", text: result.stdout }], details: { status: value.status, artifact_id: value.artifact_id } };
      } finally {
        rmSync(directory, { recursive: true, force: true });
      }
    },
  });
  pi.registerTool({
    name: "tzro",
    label: "Tzro local tools",
    description: "Local discovery and recoverable context reduction. CLI args: context [query, '--budget', '1500']; probe/search [query]; skeleton [path]; expand [hash or artifact ID]; ingest [path, '--name', table]; query [table, SQL]; compact ['--run', command]. Pass each argument as a separate string. Context defaults to 1500 tokens. Query imported tables directly; numeric columns require CAST.",
    promptSnippet: "Search code, inspect source structure, recover elided bodies, and query imported data locally",
    promptGuidelines: ["Use tzro context or probe for unfamiliar code before reading many complete files. Use expand for elided bodies. Explicit read offset/limit preserves exact source."],
    parameters: {
      type: "object",
      properties: {
        command: { type: "string", enum: commands },
        args: { type: "array", items: { type: "string" } },
      },
      required: ["command", "args"],
      additionalProperties: false,
    },
    async execute(_id: string, params: any, signal: AbortSignal, _update: any, ctx: any) {
      const args = [...params.args];
      if (params.command === "context" && !args.some((arg: string) => arg === "--budget" || arg.startsWith("--budget="))) {
        args.push("--budget", "1500");
      }
      const result = await pi.exec(binary, [params.command, ...args], { signal, timeout: 60000, cwd: ctx.cwd });
      if (result.code !== 0 || result.killed) {
        throw new Error(result.stderr || result.stdout || `tzro exited ${result.code}`);
      }
      return { content: [{ type: "text", text: result.stdout || result.stderr || "Completed." }], details: { command: params.command } };
    },
  });

  pi.on("tool_result", async (event: any, ctx: any) => {
    if (!Array.isArray(event.content)) return;
    // Explicit toolkit responses already carry their own recovery contract.
    if (event.toolName === "tzro" || event.toolName === "tzro_execute_graph") return;
    try {
      const content = event.content.map((item: any) => {
        if (item.type !== "text" || typeof item.text !== "string") return item;
        const result = JSON.parse(execFileSync(binary, ["hook", "pi-coder", "post-tool"], {
          input: JSON.stringify({ tool_name: event.toolName, tool_input: event.input, tool_output: item.text }),
          cwd: ctx.cwd, encoding: "utf8", timeout: 10000, maxBuffer: 32 * 1024 * 1024,
        }));
        return typeof result.tool_output === "string" ? { ...item, text: result.tool_output } : item;
      });
      return { content };
    } catch {
      // A failed hook preserves the native result and records an observable fallback.
      const trace = process.env.TZRO_RUNTIME_TRACE;
      if (trace) {
        try { appendFileSync(trace, JSON.stringify({ runtime: "hook:post-tool", status: "failed", tool_name: event.toolName, transform: "raw_fallback", input_bytes: event.content.reduce((n: number, c: any) => n + (c.type === "text" ? Buffer.byteLength(c.text) : 0), 0), output_bytes: event.content.reduce((n: number, c: any) => n + (c.type === "text" ? Buffer.byteLength(c.text) : 0), 0) }) + "\n", { mode: 0o600 }); } catch {}
      }
      return;
    }
  });
}
